### ISSUE TITLE
Android-x86 integration

### ISSUE THREAD

**Issue by dadreamer** [TapTrack/TCMPTappy-Android#1]
Hi!

Is it possible to integrate your Tappy External NFC service into Android-x86 build to get it working "out-of-box" for any other applications? I mean some kind of replacement of native NFC stack with Tappy NFC stack. I'd like to use an external NFC reader (like TappyUSB) in VirtualBox guest with Android-x86. Are there any instructions for how could I make a new build along with your service? I also need HCE functionality, if your SDK offers it.

**Comment by lvanoort** [comment]
Hi, we'll need a bit more information to be sure, but I think what you're after is most likely not possible. If I understand correctly, you want to install existing Android apps on the device and have them use an external NFC reader as if it was the on-board NFC without modifying the apps themselves or the underlying OS. If that is correct, it can't be done because Android doesn't let you supplant the built-in stack or use an external device for NFC at runtime. Hypothetically, you could download the Android source code from the AOSP modify the OS to support using external readers, but that would be a pretty significant undertaking.

**Comment by dadreamer** [comment]
> If I understand correctly, you want to install existing Android apps on the device and have them use an external NFC reader as if it was the on-board NFC without modifying the apps themselves

That's correct. I have some 3rd party apps, which require NFC and HCE, so I want to make them work with the external NFC reader as it was a built-in one.

> without modifying ... the underlying OS

[Android-x86](http://www.android-x86.org/) is an open-source project (Apache Public License, GPL), so I may modify its code, add or remove components and other things. At the moment I have a workable image with native NFC service activated, but I'm unable to use any NFC hardware with it.

> Hypothetically, you could download the Android source code from the AOSP modify the OS to support using external readers, but that would be a pretty significant undertaking.

Well, I hoped that someone already did it before and could show me where to start. I had a contact with [Thomas Skjølberg](https://github.com/skjolber) (a creator of [External NFC Service API](https://github.com/skjolber/external-nfc-api) for ACS readers) and he said that it's possible. But it seems that he's not going to adapt his service at the moment. And I don't know how to do it on my own.

At your website I saw that you develop a ready-to-use applications. Might you implement this idea in any appropriate form (a tweaked service + iso or maybe an app package (like The Open GApps Project) + instructions for the end users)?

**Comment by dadreamer** [comment]
Would it be possible to bring this idea to life on a paid basis? What would it take for this?..

**Comment by dshalaby** [comment]
Please contact us at info@taptrack.com.
